package pw.ozro.app;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


import pw.ozro.app.Repository;
import pw.ozro.app.Role;


public class RoleRepository extends Repository<Role> {
    RoleRepository(Connection c) throws SQLException {
        super(c);
    }

    @Override
    public String table() { return "t_sys_roles"; }

    @Override
    protected String queryCreateTable() {
        return ("create table t_sys_roles ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
                + "role_id BIGINT,"
                + "user_id BIGINT,"
                + ")"
               );
    }

    @Override
    protected String queryCreate() {
        return "(role_id, user_id) values (?, ?)";
    }

    @Override
    protected String queryUpdate() {
        return "(role_id, user_id) values (?, ?)";
    }

    @Override
    protected void bindCreate(PreparedStatement ps, Role entity) throws SQLException {
        ps.setInt(2, entity.role_id);
        ps.setInt(2, entity.user_id);
    }

    @Override
    protected void bindUpdate(PreparedStatement ps, Role entity) throws SQLException {
        bindCreate(ps, entity);
        ps.setInt(3, entity.id());
    }

    @Override
    protected String selectColumns() {
        return "role_id, user_id";
    }

    @Override
    protected Role extractSelected(ResultSet rs) throws SQLException {
        Role entity = new Role(
            rs.getInt("role_id")
            , rs.getInt("user_id")
        );
        return entity;
    }
}
